version: '3.3'

volumes:
  db_data:
  static_value:
  media_value:

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - .env
  backend:
    image: antisyslik/foodgram-backend:latest
    restart: always
    volumes:
      - static_value:/app/static_backend/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - .env
  frontend:
    image: antisyslik/foodgram-frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend
  nginx:
    image: nginx:1.19.6
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ../frontend/build:/usr/share/nginx/html/
      - /docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static_backend/
      - media_value:/var/html/media/
    restart: always
    depends_on:
      - frontend
