# Generated by Django 4.2.1 on 2023-05-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='app/', verbose_name='Изображение'),
        ),
    ]
